### ISSUE TITLE
[BUG] /loc di interior

### ISSUE THREAD

**Issue by BossSyno** [wjcnr/issues#10]
**Deskripsi Bug**
/loc kepada player yang berada di interior menyebabkan lokasinya tidak terketahui
**Cara Melihat/Mendapat Bug**
Langkah-langkah agar bug bisa terlihat:

1./loc [id player yang ada di interior]
2.
3.
4.
5.
...
**Hal yang harusnya terjadi**
/loc yang memperlihatkan lokasi dari player yang berada di interior tersebut
**Screenshots**
![image](https://user-images.githubusercontent.com/80107710/110199926-7d250a00-7e8d-11eb-854c-264e4da9cf49.png)

**Versi Server**
WJCNRv.3.0.2
**Penjelasan Tambahan**
Reported By Atsumu

**Comment by Fairuz-Afdhal** [comment]
Sekarang akan menunjukan lokasi interior player itu masuk
