### ISSUE TITLE
[BUG] Lokasi rob di interior bank

### ISSUE THREAD

**Issue by equinnoxy** [wjcnr/issues#13]
**Deskripsi Bug**
Lokasi bank hanya tertulis "!"

**Cara Melihat/Mendapat Bug**
Langkah-langkah agar bug bisa terlihat:

1. Saat rob isi brankas bank
...
**Hal yang harusnya terjadi**
Tertulis lokasi Downtown di ! tersebut
seperti Bank of San Fierro - Safe 1 in Downtown

**Screenshots**
![sa-mp-150](https://user-images.githubusercontent.com/80108479/110213070-0e69a000-7ed1-11eb-84f3-b1b94e8d5c2e.png)

**Versi Server**
3.0.3

**Penjelasan Tambahan**
gw ganteng (2)

**Comment by Fairuz-Afdhal** [comment]
Sudah difix berbarengan dengan #10
