### ISSUE TITLE
[BUG] /osuspend 

### ISSUE THREAD

**Issue by BossSyno** [wjcnr/issues#15]
**Deskripsi Bug**
Bug di /osuspend tidak bekerja
player yang telah di osuspend masih bisa login
**Cara Melihat/Mendapat Bug**
Langkah-langkah agar bug bisa terlihat:

1./osuspend
2.
3.
4.
5.
...
**Hal yang harusnya terjadi**
Player yang offline bisa tersuspend offline dengan adanya cmd /osuspend
**Screenshots**
![image](https://user-images.githubusercontent.com/80107710/110233639-cd689e80-7f57-11eb-92e9-f2cdd8049eff.png)

**Versi Server**
WJCNRv.3.0.3
**Penjelasan Tambahan**

**Comment by Davin3110** [comment]
menggokil

**Comment by AsuraZX** [comment]
gw dah type /osuspend moni 0 30 ammo hack malah begitu
