### ISSUE TITLE
[BUG] Admin Spawn

### ISSUE THREAD

**Issue by BossSyno** [wjcnr/issues#36]
**Deskripsi Bug**
Bug /aspawn kepada player yg notspawned
setelah di aspawn,giliran kita yang notspawned
**Cara Melihat/Mendapat Bug**
Langkah-langkah agar bug bisa terlihat:

1. /aspawn ke player yang notspawned
2.
3.
4.
5.
...
**Hal yang harusnya terjadi**
harusnya kita bisa melakukan cmd lain setelah aspawn
**Screenshots**

**Versi Server**
WJCNRv.3.0.4
**Penjelasan Tambahan**

**Comment by zidanirfani** [comment]
.
