### ISSUE TITLE
[BUG] /jaillist

### ISSUE THREAD

**Issue by BossSyno** [wjcnr/issues#37]
**Deskripsi Bug**
/jaillist tidak memperlihatkan pemain yang seharusnya di penjara,baik itu di lv,ls,sf,bahkan alcatraz,sehingga tidak bisa di bail
**Cara Melihat/Mendapat Bug**
Langkah-langkah agar bug bisa terlihat:

1./jaillist
2.
3.
4.
5.
...
**Hal yang harusnya terjadi**
pemain yang di penjara dengan reason apapun (avoid,arrested) dll,bisa terlihat di /jaillist
**Screenshots**
![image](https://user-images.githubusercontent.com/80107710/110936906-2bd0bb00-8364-11eb-9fe7-5a0f8754e2c8.png)

**Versi Server**
WJCNRv.3.0.4
**Penjelasan Tambahan**
dengan adanya bug /jaillist,maka player yang sudah masuk tidak bisa di /bail,bahkan /unjail

**Comment by Fairuz-Afdhal** [comment]
Sama dengan bug jail.
