### ISSUE TITLE
[BUG] Alcatraz

### ISSUE THREAD

**Issue by BossSyno** [wjcnr/issues#41]
**Deskripsi Bug**
Bug Jail yang berada di alcatraz,
bagi mereka yang class selain civil,bisa menggunakan /changeclass untuk kabur dari alcatraz
**Cara Melihat/Mendapat Bug**
Langkah-langkah agar bug bisa terlihat:

1. /changeclass ( selain civil )
2.
3.
4.
5.
...
**Hal yang harusnya terjadi**
Tetap terjail meskipun /changeclass di lakukan
**Screenshots**

**Versi Server**
WJCNRv.3.0.4
**Penjelasan Tambahan**

**Comment by Fairuz-Afdhal** [comment]
Sama dnegan bug jail.
