### ISSUE TITLE
[BUG]Reason Banned

### ISSUE THREAD

**Issue by Davin3110** [wjcnr/issues#58]
**Deskripsi Bug**
kalo ngeban orang reasonnya malah jadi IP
**Cara Melihat/Mendapat Bug**
Langkah-langkah agar bug bisa terlihat:

1. /ban [id] 
2.
3.
4.
5.
...
**Hal yang harusnya terjadi**
reason yang keluar bukan ip
**Screenshots**
https://ibb.co/K9kdrQ8
**Versi Server**
3
**Penjelasan Tambahan**
**LESS GOOOOO**

**Comment by Fairuz-Afdhal** [comment]
fixed
