### ISSUE TITLE
[BUG] Bug pada /loc

### ISSUE THREAD

**Issue by Ichiroki** [wjcnr/issues#6]
**Deskripsi Bug**

**Cara Melihat/Mendapat Bug**
Langkah-langkah agar bug bisa terlihat:

1. Ketik /loc
2.
3.
4.
5.
...
**Hal yang harusnya terjadi**
Hal yang seharusnya terjadi mendeteksi lokasi pada kriminal, namun mendeteksi lokasi player yang menggunakan cmd tersebut
**Screenshots**
![sa-mp-176](https://user-images.githubusercontent.com/76273623/110193061-6a4a0f80-7e64-11eb-8ef7-dcfa66abdf1c.png)
![sa-mp-177](https://user-images.githubusercontent.com/76273623/110193082-79c95880-7e64-11eb-94ff-d9888a3bd782.png)

**Versi Server**

**Penjelasan Tambahan**

**Comment by Fairuz-Afdhal** [comment]
Sudah difix
