### ISSUE TITLE
[BUG] Rooftop

### ISSUE THREAD

**Issue by equinnoxy** [wjcnr/issues#63]
**Deskripsi Bug**

**Cara Melihat/Mendapat Bug**
Langkah-langkah agar bug bisa terlihat:

1. membeli vip diamond 
2.
3.
4.
5.
...
**Hal yang harusnya terjadi**
membeli vip diamond mendapatkan rooftop /notes

**Screenshots**

**Versi Server**

**Penjelasan Tambahan**
LESGO

**Comment by Vyrize** [comment]
*Note tambahkan /editrooftop karena saat pembuatan tidak sengaja tekan esc maka tidak bisa di edit lagi
