### ISSUE TITLE
[BUG] ID 32 Keatas

### ISSUE THREAD

**Issue by BossSyno** [wjcnr/issues#8]
**Deskripsi Bug**
Bug pada id 32 keatas
Terjadi ketika /stats 32 > game > tidak terlihat
kemudian xp nya ter reset sendiri.
Kemudian id 32 keatas bisa melihat admin log beserta spec secara tiba tiba

**Cara Melihat/Mendapat Bug**
Langkah-langkah agar bug bisa terlihat:

1./stats 32 > game > nothing happend
2.
3.
4.
5.
...
**Hal yang harusnya terjadi**
Admin log hanya tersedia untuk admin,dan tidak akan terjadi apa apa jika player yang melihat
/stats 32 > game > harusnya mengeluarkan box yang isiinya berupa stats player tersebut
**Screenshots**

**Versi Server**
WJCNRv.3.0.2
**Penjelasan Tambahan**
Player dengan id 32 keatas bisa relog untuk mendapatkan id yg lbih kecil jika tersedia

**Comment by Fairuz-Afdhal** [comment]
Sudah kefix, namun butuh improvement dari sisi performa server.
